package com.nestor.springabstractcacheredis.po;

import java.io.Serializable;
import java.math.BigDecimal;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table course_param
 */
public class CourseParam extends BaseModel implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_param.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   课程名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_param.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   授课老师
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_param.instructor
     *
     * @mbg.generated
     */
    private String instructor;

    /**
     * Database Column Remarks:
     *   学分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_param.credit
     *
     * @mbg.generated
     */
    private BigDecimal credit;

    /**
     * Database Column Remarks:
     *   课时
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_param.lession_period
     *
     * @mbg.generated
     */
    private BigDecimal lessionPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course_param
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_param.id
     *
     * @return the value of course_param.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_param.id
     *
     * @param id the value for course_param.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_param.name
     *
     * @return the value of course_param.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_param.name
     *
     * @param name the value for course_param.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_param.instructor
     *
     * @return the value of course_param.instructor
     *
     * @mbg.generated
     */
    public String getInstructor() {
        return instructor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_param.instructor
     *
     * @param instructor the value for course_param.instructor
     *
     * @mbg.generated
     */
    public void setInstructor(String instructor) {
        this.instructor = instructor == null ? null : instructor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_param.credit
     *
     * @return the value of course_param.credit
     *
     * @mbg.generated
     */
    public BigDecimal getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_param.credit
     *
     * @param credit the value for course_param.credit
     *
     * @mbg.generated
     */
    public void setCredit(BigDecimal credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_param.lession_period
     *
     * @return the value of course_param.lession_period
     *
     * @mbg.generated
     */
    public BigDecimal getLessionPeriod() {
        return lessionPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_param.lession_period
     *
     * @param lessionPeriod the value for course_param.lession_period
     *
     * @mbg.generated
     */
    public void setLessionPeriod(BigDecimal lessionPeriod) {
        this.lessionPeriod = lessionPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_param
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
    }
}