server:
  servlet:
    context-path: /mybatis-demo
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/mybatis-demo?useUniCode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useCursorFetch=true&rewriteBatchedStatements=true
    url: jdbc:mysql://localhost:3306/mybatis-demo?useUniCode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
#    url: jdbc:mysql://localhost:3306/mybatis-demo?useUniCode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 3600000
      connection-timeout: 5000
      connection-test-query: select 1
#      auto-commit: false

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
management:
  endpoints:
    web:
      exposure:
        include: "*"