server:
  servlet:
    context-path: /mybatis-plus-demo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis-demo?useUniCode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useCursorFetch=true
    #    url: jdbc:mysql://localhost:3306/mybatis-demo?useUniCode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 20
#      minimum-idle: 10
#      idle-timeout: 3600000
#      connection-timeout: 5000
#      connection-test-query: select 1

management:
  endpoints:
    web:
      exposure:
        include: "*"